// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passenger.proto

package passenger

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseCode struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseCode) Reset()         { *m = ResponseCode{} }
func (m *ResponseCode) String() string { return proto.CompactTextString(m) }
func (*ResponseCode) ProtoMessage()    {}
func (*ResponseCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{0}
}

func (m *ResponseCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCode.Unmarshal(m, b)
}
func (m *ResponseCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCode.Marshal(b, m, deterministic)
}
func (m *ResponseCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCode.Merge(m, src)
}
func (m *ResponseCode) XXX_Size() int {
	return xxx_messageInfo_ResponseCode.Size(m)
}
func (m *ResponseCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCode.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCode proto.InternalMessageInfo

func (m *ResponseCode) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseCode) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PassengerFeedback struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerID          int32    `protobuf:"varint,2,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	Feedback             string   `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerFeedback) Reset()         { *m = PassengerFeedback{} }
func (m *PassengerFeedback) String() string { return proto.CompactTextString(m) }
func (*PassengerFeedback) ProtoMessage()    {}
func (*PassengerFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{1}
}

func (m *PassengerFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerFeedback.Unmarshal(m, b)
}
func (m *PassengerFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerFeedback.Marshal(b, m, deterministic)
}
func (m *PassengerFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerFeedback.Merge(m, src)
}
func (m *PassengerFeedback) XXX_Size() int {
	return xxx_messageInfo_PassengerFeedback.Size(m)
}
func (m *PassengerFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerFeedback proto.InternalMessageInfo

func (m *PassengerFeedback) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *PassengerFeedback) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

func (m *PassengerFeedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type AddPassengerFeedbackResponse struct {
	ResponseCode         *ResponseCode `protobuf:"bytes,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddPassengerFeedbackResponse) Reset()         { *m = AddPassengerFeedbackResponse{} }
func (m *AddPassengerFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*AddPassengerFeedbackResponse) ProtoMessage()    {}
func (*AddPassengerFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{2}
}

func (m *AddPassengerFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPassengerFeedbackResponse.Unmarshal(m, b)
}
func (m *AddPassengerFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPassengerFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *AddPassengerFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPassengerFeedbackResponse.Merge(m, src)
}
func (m *AddPassengerFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_AddPassengerFeedbackResponse.Size(m)
}
func (m *AddPassengerFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPassengerFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPassengerFeedbackResponse proto.InternalMessageInfo

func (m *AddPassengerFeedbackResponse) GetResponseCode() *ResponseCode {
	if m != nil {
		return m.ResponseCode
	}
	return nil
}

type GetPassengerFeedbackRequest struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerID          int32    `protobuf:"varint,2,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPassengerFeedbackRequest) Reset()         { *m = GetPassengerFeedbackRequest{} }
func (m *GetPassengerFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*GetPassengerFeedbackRequest) ProtoMessage()    {}
func (*GetPassengerFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{3}
}

func (m *GetPassengerFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPassengerFeedbackRequest.Unmarshal(m, b)
}
func (m *GetPassengerFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPassengerFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *GetPassengerFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPassengerFeedbackRequest.Merge(m, src)
}
func (m *GetPassengerFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_GetPassengerFeedbackRequest.Size(m)
}
func (m *GetPassengerFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPassengerFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPassengerFeedbackRequest proto.InternalMessageInfo

func (m *GetPassengerFeedbackRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *GetPassengerFeedbackRequest) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type GetPassengerFeedbackResponse struct {
	ResponseCode         *ResponseCode      `protobuf:"bytes,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	PassengerFeedback    *PassengerFeedback `protobuf:"bytes,2,opt,name=passengerFeedback,proto3" json:"passengerFeedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPassengerFeedbackResponse) Reset()         { *m = GetPassengerFeedbackResponse{} }
func (m *GetPassengerFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*GetPassengerFeedbackResponse) ProtoMessage()    {}
func (*GetPassengerFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{4}
}

func (m *GetPassengerFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPassengerFeedbackResponse.Unmarshal(m, b)
}
func (m *GetPassengerFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPassengerFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *GetPassengerFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPassengerFeedbackResponse.Merge(m, src)
}
func (m *GetPassengerFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_GetPassengerFeedbackResponse.Size(m)
}
func (m *GetPassengerFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPassengerFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPassengerFeedbackResponse proto.InternalMessageInfo

func (m *GetPassengerFeedbackResponse) GetResponseCode() *ResponseCode {
	if m != nil {
		return m.ResponseCode
	}
	return nil
}

func (m *GetPassengerFeedbackResponse) GetPassengerFeedback() *PassengerFeedback {
	if m != nil {
		return m.PassengerFeedback
	}
	return nil
}

type GetPassengerFeedbacksResponse struct {
	ResponseCode         *ResponseCode        `protobuf:"bytes,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	PassengerFeedbacks   []*PassengerFeedback `protobuf:"bytes,2,rep,name=passengerFeedbacks,proto3" json:"passengerFeedbacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetPassengerFeedbacksResponse) Reset()         { *m = GetPassengerFeedbacksResponse{} }
func (m *GetPassengerFeedbacksResponse) String() string { return proto.CompactTextString(m) }
func (*GetPassengerFeedbacksResponse) ProtoMessage()    {}
func (*GetPassengerFeedbacksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{5}
}

func (m *GetPassengerFeedbacksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPassengerFeedbacksResponse.Unmarshal(m, b)
}
func (m *GetPassengerFeedbacksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPassengerFeedbacksResponse.Marshal(b, m, deterministic)
}
func (m *GetPassengerFeedbacksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPassengerFeedbacksResponse.Merge(m, src)
}
func (m *GetPassengerFeedbacksResponse) XXX_Size() int {
	return xxx_messageInfo_GetPassengerFeedbacksResponse.Size(m)
}
func (m *GetPassengerFeedbacksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPassengerFeedbacksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPassengerFeedbacksResponse proto.InternalMessageInfo

func (m *GetPassengerFeedbacksResponse) GetResponseCode() *ResponseCode {
	if m != nil {
		return m.ResponseCode
	}
	return nil
}

func (m *GetPassengerFeedbacksResponse) GetPassengerFeedbacks() []*PassengerFeedback {
	if m != nil {
		return m.PassengerFeedbacks
	}
	return nil
}

type DeletePassengerFeedbackRequest struct {
	PassengerID          int32    `protobuf:"varint,1,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePassengerFeedbackRequest) Reset()         { *m = DeletePassengerFeedbackRequest{} }
func (m *DeletePassengerFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePassengerFeedbackRequest) ProtoMessage()    {}
func (*DeletePassengerFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{6}
}

func (m *DeletePassengerFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePassengerFeedbackRequest.Unmarshal(m, b)
}
func (m *DeletePassengerFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePassengerFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *DeletePassengerFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePassengerFeedbackRequest.Merge(m, src)
}
func (m *DeletePassengerFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePassengerFeedbackRequest.Size(m)
}
func (m *DeletePassengerFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePassengerFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePassengerFeedbackRequest proto.InternalMessageInfo

func (m *DeletePassengerFeedbackRequest) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type DeletePassengerFeedbackResponse struct {
	ResponseCode         *ResponseCode `protobuf:"bytes,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeletePassengerFeedbackResponse) Reset()         { *m = DeletePassengerFeedbackResponse{} }
func (m *DeletePassengerFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePassengerFeedbackResponse) ProtoMessage()    {}
func (*DeletePassengerFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{7}
}

func (m *DeletePassengerFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePassengerFeedbackResponse.Unmarshal(m, b)
}
func (m *DeletePassengerFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePassengerFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *DeletePassengerFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePassengerFeedbackResponse.Merge(m, src)
}
func (m *DeletePassengerFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePassengerFeedbackResponse.Size(m)
}
func (m *DeletePassengerFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePassengerFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePassengerFeedbackResponse proto.InternalMessageInfo

func (m *DeletePassengerFeedbackResponse) GetResponseCode() *ResponseCode {
	if m != nil {
		return m.ResponseCode
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseCode)(nil), "ResponseCode")
	proto.RegisterType((*PassengerFeedback)(nil), "PassengerFeedback")
	proto.RegisterType((*AddPassengerFeedbackResponse)(nil), "AddPassengerFeedbackResponse")
	proto.RegisterType((*GetPassengerFeedbackRequest)(nil), "GetPassengerFeedbackRequest")
	proto.RegisterType((*GetPassengerFeedbackResponse)(nil), "GetPassengerFeedbackResponse")
	proto.RegisterType((*GetPassengerFeedbacksResponse)(nil), "GetPassengerFeedbacksResponse")
	proto.RegisterType((*DeletePassengerFeedbackRequest)(nil), "DeletePassengerFeedbackRequest")
	proto.RegisterType((*DeletePassengerFeedbackResponse)(nil), "DeletePassengerFeedbackResponse")
}

func init() { proto.RegisterFile("passenger.proto", fileDescriptor_59870f8f4446d21a) }

var fileDescriptor_59870f8f4446d21a = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0xad, 0x55, 0x3b, 0xad, 0x68, 0x07, 0x0f, 0x21, 0xf6, 0x27, 0xee, 0xa9, 0xa7, 0x05,
	0xeb, 0xd5, 0x83, 0xa6, 0x45, 0xe9, 0x4d, 0xa3, 0x0f, 0x60, 0xda, 0x8c, 0xa1, 0x54, 0xbb, 0x31,
	0x1b, 0x05, 0x9f, 0xc1, 0xa3, 0xe0, 0xf3, 0x8a, 0xc1, 0x84, 0xd5, 0x6c, 0x56, 0xa8, 0xde, 0xb2,
	0xc3, 0xf0, 0xfd, 0xcc, 0xf7, 0x11, 0xd8, 0x8d, 0x03, 0x29, 0x69, 0x15, 0x51, 0xc2, 0xe3, 0x44,
	0xa4, 0x82, 0x9d, 0x40, 0xdb, 0x27, 0x19, 0x8b, 0x95, 0xa4, 0xb1, 0x08, 0x09, 0x11, 0x36, 0xe6,
	0x22, 0x24, 0xdb, 0x72, 0xad, 0x61, 0xc3, 0xcf, 0xbe, 0xd1, 0x86, 0xad, 0x07, 0x92, 0x32, 0x88,
	0xc8, 0xae, 0xb9, 0xd6, 0xb0, 0xe9, 0xe7, 0x4f, 0x26, 0xa1, 0x73, 0x99, 0x03, 0x9e, 0x13, 0x85,
	0xb3, 0x60, 0xbe, 0x44, 0x17, 0x5a, 0x33, 0x21, 0x96, 0x8b, 0x55, 0x34, 0xce, 0x91, 0x9a, 0xbe,
	0x3a, 0xfa, 0xdc, 0x28, 0x74, 0x4c, 0x27, 0x19, 0x68, 0xc3, 0x57, 0x47, 0xe8, 0xc0, 0xf6, 0xdd,
	0x17, 0x9e, 0x5d, 0xcf, 0x00, 0x8a, 0x37, 0xbb, 0x82, 0xee, 0x59, 0x18, 0x96, 0x78, 0x73, 0x1b,
	0x78, 0x04, 0xed, 0x44, 0xb1, 0x94, 0x09, 0x68, 0x8d, 0x76, 0xb8, 0xea, 0xd3, 0xff, 0xb6, 0xc2,
	0x02, 0x38, 0xb8, 0xa0, 0x54, 0x03, 0xf9, 0xf8, 0x44, 0x32, 0xfd, 0x0f, 0x47, 0xec, 0xcd, 0x82,
	0xae, 0x9e, 0x63, 0x6d, 0xd9, 0x78, 0x0a, 0x9d, 0xf8, 0x27, 0x5e, 0xc6, 0xdd, 0x1a, 0x21, 0x2f,
	0x33, 0x95, 0x97, 0xd9, 0xbb, 0x05, 0x3d, 0x9d, 0x2a, 0xf9, 0x17, 0x59, 0x1e, 0x60, 0x89, 0x49,
	0xda, 0x35, 0xb7, 0x5e, 0xa1, 0x4b, 0xb3, 0xcd, 0x3c, 0xe8, 0x4f, 0xe8, 0x9e, 0x52, 0x32, 0x85,
	0xa2, 0x9e, 0xdc, 0x2a, 0x9f, 0xfc, 0x06, 0x06, 0x95, 0x18, 0x6b, 0xbb, 0x1b, 0xbd, 0xd6, 0x61,
	0xaf, 0x00, 0xbc, 0xa6, 0xe4, 0x79, 0x31, 0x27, 0x9c, 0xc2, 0xbe, 0xae, 0x93, 0xa8, 0xb1, 0xeb,
	0xf4, 0xb8, 0xb1, 0xbe, 0x01, 0x1c, 0xea, 0x12, 0xf1, 0x5e, 0x8a, 0xd1, 0x34, 0xc4, 0x2e, 0x37,
	0xf4, 0xd5, 0xe9, 0x73, 0x73, 0xa6, 0xb7, 0x55, 0x14, 0x9e, 0x52, 0x69, 0x33, 0x45, 0x8f, 0x1b,
	0xcb, 0x1c, 0x01, 0xab, 0x38, 0xbd, 0xea, 0x62, 0xc0, 0xcd, 0x19, 0x3b, 0x2e, 0xff, 0x25, 0xc0,
	0xd9, 0x66, 0xf6, 0x1b, 0x3b, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x06, 0xd3, 0xdf, 0xd9,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PassengerServiceClient is the client API for PassengerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PassengerServiceClient interface {
	AddPassengerFeedback(ctx context.Context, in *PassengerFeedback, opts ...grpc.CallOption) (*AddPassengerFeedbackResponse, error)
	GetPassengerFeedbackByPassengerId(ctx context.Context, in *GetPassengerFeedbackRequest, opts ...grpc.CallOption) (*GetPassengerFeedbacksResponse, error)
	GetPassengerFeedbackByBookingCode(ctx context.Context, in *GetPassengerFeedbackRequest, opts ...grpc.CallOption) (*GetPassengerFeedbackResponse, error)
	DeletePassengerFeedbackPassengerId(ctx context.Context, in *DeletePassengerFeedbackRequest, opts ...grpc.CallOption) (*DeletePassengerFeedbackResponse, error)
}

type passengerServiceClient struct {
	cc *grpc.ClientConn
}

func NewPassengerServiceClient(cc *grpc.ClientConn) PassengerServiceClient {
	return &passengerServiceClient{cc}
}

func (c *passengerServiceClient) AddPassengerFeedback(ctx context.Context, in *PassengerFeedback, opts ...grpc.CallOption) (*AddPassengerFeedbackResponse, error) {
	out := new(AddPassengerFeedbackResponse)
	err := c.cc.Invoke(ctx, "/PassengerService/AddPassengerFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) GetPassengerFeedbackByPassengerId(ctx context.Context, in *GetPassengerFeedbackRequest, opts ...grpc.CallOption) (*GetPassengerFeedbacksResponse, error) {
	out := new(GetPassengerFeedbacksResponse)
	err := c.cc.Invoke(ctx, "/PassengerService/GetPassengerFeedbackByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) GetPassengerFeedbackByBookingCode(ctx context.Context, in *GetPassengerFeedbackRequest, opts ...grpc.CallOption) (*GetPassengerFeedbackResponse, error) {
	out := new(GetPassengerFeedbackResponse)
	err := c.cc.Invoke(ctx, "/PassengerService/GetPassengerFeedbackByBookingCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) DeletePassengerFeedbackPassengerId(ctx context.Context, in *DeletePassengerFeedbackRequest, opts ...grpc.CallOption) (*DeletePassengerFeedbackResponse, error) {
	out := new(DeletePassengerFeedbackResponse)
	err := c.cc.Invoke(ctx, "/PassengerService/DeletePassengerFeedbackPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassengerServiceServer is the server API for PassengerService service.
type PassengerServiceServer interface {
	AddPassengerFeedback(context.Context, *PassengerFeedback) (*AddPassengerFeedbackResponse, error)
	GetPassengerFeedbackByPassengerId(context.Context, *GetPassengerFeedbackRequest) (*GetPassengerFeedbacksResponse, error)
	GetPassengerFeedbackByBookingCode(context.Context, *GetPassengerFeedbackRequest) (*GetPassengerFeedbackResponse, error)
	DeletePassengerFeedbackPassengerId(context.Context, *DeletePassengerFeedbackRequest) (*DeletePassengerFeedbackResponse, error)
}

// UnimplementedPassengerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPassengerServiceServer struct {
}

func (*UnimplementedPassengerServiceServer) AddPassengerFeedback(ctx context.Context, req *PassengerFeedback) (*AddPassengerFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPassengerFeedback not implemented")
}
func (*UnimplementedPassengerServiceServer) GetPassengerFeedbackByPassengerId(ctx context.Context, req *GetPassengerFeedbackRequest) (*GetPassengerFeedbacksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPassengerFeedbackByPassengerId not implemented")
}
func (*UnimplementedPassengerServiceServer) GetPassengerFeedbackByBookingCode(ctx context.Context, req *GetPassengerFeedbackRequest) (*GetPassengerFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPassengerFeedbackByBookingCode not implemented")
}
func (*UnimplementedPassengerServiceServer) DeletePassengerFeedbackPassengerId(ctx context.Context, req *DeletePassengerFeedbackRequest) (*DeletePassengerFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePassengerFeedbackPassengerId not implemented")
}

func RegisterPassengerServiceServer(s *grpc.Server, srv PassengerServiceServer) {
	s.RegisterService(&_PassengerService_serviceDesc, srv)
}

func _PassengerService_AddPassengerFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerFeedback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).AddPassengerFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PassengerService/AddPassengerFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).AddPassengerFeedback(ctx, req.(*PassengerFeedback))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_GetPassengerFeedbackByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassengerFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).GetPassengerFeedbackByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PassengerService/GetPassengerFeedbackByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).GetPassengerFeedbackByPassengerId(ctx, req.(*GetPassengerFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_GetPassengerFeedbackByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassengerFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).GetPassengerFeedbackByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PassengerService/GetPassengerFeedbackByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).GetPassengerFeedbackByBookingCode(ctx, req.(*GetPassengerFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_DeletePassengerFeedbackPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePassengerFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).DeletePassengerFeedbackPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PassengerService/DeletePassengerFeedbackPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).DeletePassengerFeedbackPassengerId(ctx, req.(*DeletePassengerFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PassengerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PassengerService",
	HandlerType: (*PassengerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPassengerFeedback",
			Handler:    _PassengerService_AddPassengerFeedback_Handler,
		},
		{
			MethodName: "GetPassengerFeedbackByPassengerId",
			Handler:    _PassengerService_GetPassengerFeedbackByPassengerId_Handler,
		},
		{
			MethodName: "GetPassengerFeedbackByBookingCode",
			Handler:    _PassengerService_GetPassengerFeedbackByBookingCode_Handler,
		},
		{
			MethodName: "DeletePassengerFeedbackPassengerId",
			Handler:    _PassengerService_DeletePassengerFeedbackPassengerId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "passenger.proto",
}
